name: build dsm
on:
  workflow_dispatch:
  schedule:
    - cron: "0 0 1 * *"
  push:
    branches:
      - master
    paths:
      - dsm/**
jobs:
  push:
    name: "dsm:${{ matrix.dsm }}"
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        dsm:
          - source
          - os
    steps:
      - uses: actions/checkout@v3
      - uses: docker/setup-buildx-action@v2
        with:
          buildkitd-flags: --debug
      - uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.repository_owner }}
          password: ${{ secrets.REGISTRY_TOKEN }}
      - uses: docker/build-push-action@v4
        with:
          context: ./dsm/${{ matrix.dsm }}
          file: ./dsm/${{ matrix.dsm }}/Dockerfile
          platforms: linux/amd64
          push: true
          tags: |
            ghcr.io/foudugame/pterodactyl/dsm:${{ matrix.dsm }}
